"""Rename the plane to *procedural* and conform it to the design.

Design authority: ``.claude/reports/2026-06-04-procedural-experiential-memory-design.md``
(§1 decisions table, §18.1, §18.2, §18.9.0) plus the 2026-06-10 JG
decisions: the plane is named **procedural** everywhere; no ``user``
scope; cases are NOTES (``role='case'`` in the hidden system vault),
never rows on this table.

Part A — RENAME (the plane is procedural, not experiential):

  * 5 tables: ``experiential_*`` → ``procedural_*``
    (entries, entry_versions, sources, pins, derivation_queue).
  * Every index and constraint on those tables whose name contains
    ``experiential`` (renamed dynamically via catalog scan so nothing
    is missed).
  * The IMMUTABLE tags wrapper function
    ``memex_experiential_tags_to_text`` → ``memex_procedural_tags_to_text``
    (the generated tsvector column tracks the function by OID, so the
    rename is dependency-safe).
  * The hidden system vault seeded by 063: name ``experiential`` →
    ``procedural``.

Part B — CONFORM:

  1. **kind narrows to ('procedure', 'strategy').** ``case`` rows are
     deleted (unreleased branch; cases-are-notes decision). FK CASCADE
     removes their versions / sources / pins.
  2. **No ``user`` scope.** ``scope='user'`` rows are re-scoped to
     ``global`` where the identity anchor stays unique; collisions are
     deleted. ``user``-context pins are deleted.
  3. **Anchor shape per §18.1.** Procedure ≡ (scope, verb, context) —
     both required. Strategy ≡ (scope, verb, NULL) — verb required,
     context forbidden (a strategy is the projection over all
     procedures sharing (scope, verb)).
  4. **One retrieval embedding.** ``body_embedding`` (+ HNSW index and
     scope CHECK) is dropped. The design embeds the *trigger* only —
     spike §19.1: trigger-only beats full-body 18/20 vs 15/20 top-1.
     Body text stays reachable via the BM25 leg. The trigger HNSW
     partial index loses its ``kind='case'`` predicate.
  5. **tsvector includes the trigger** (title + summary + trigger +
     body + tags) so the BM25 leg also sees the retrieval key.

Downgrade restores the 061-063 shape (names + constraints +
body_embedding + old tsvector). Deleted rows are NOT restored.

Revision ID: 064_two_kind_plane
Revises: 063_experiential_seed
Create Date: 2026-06-10
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '064_two_kind_plane'
down_revision: str | None = '063_experiential_seed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_TABLE_RENAMES: list[tuple[str, str]] = [
    ('experiential_entries', 'procedural_entries'),
    ('experiential_entry_versions', 'procedural_entry_versions'),
    ('experiential_sources', 'procedural_sources'),
    ('experiential_pins', 'procedural_pins'),
    ('experiential_derivation_queue', 'procedural_derivation_queue'),
]

_NEW_TSVECTOR_SQL = (
    "to_tsvector('english'::regconfig, "
    "coalesce(title, '') || ' ' || "
    "coalesce(summary, '') || ' ' || "
    "coalesce(trigger, '') || ' ' || "
    "coalesce(body, '') || ' ' || "
    "coalesce(memex_procedural_tags_to_text(tags), ''))"
)

_OLD_TSVECTOR_SQL = (
    "to_tsvector('english'::regconfig, "
    "coalesce(title, '') || ' ' || "
    "coalesce(summary, '') || ' ' || "
    "coalesce(body, '') || ' ' || "
    "coalesce(memex_experiential_tags_to_text(tags), ''))"
)

# Catalog-driven rename of every index / constraint on the plane's
# tables whose name carries the old vocabulary. Names not matching are
# left alone; PK/FK indexes created implicitly are covered because
# their autogenerated names embed the (old) table name.
_RENAME_INDEXES_SQL = """
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT indexname FROM pg_indexes
        WHERE schemaname = current_schema()
          AND tablename IN (
            'procedural_entries', 'procedural_entry_versions',
            'procedural_sources', 'procedural_pins',
            'procedural_derivation_queue')
          AND indexname LIKE '%experiential%'
    LOOP
        EXECUTE format(
            'ALTER INDEX %I RENAME TO %I',
            r.indexname, replace(r.indexname, 'experiential', 'procedural'));
    END LOOP;
END $$;
"""

_RENAME_CONSTRAINTS_SQL = """
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.conname, t.relname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = current_schema()
          AND t.relname IN (
            'procedural_entries', 'procedural_entry_versions',
            'procedural_sources', 'procedural_pins',
            'procedural_derivation_queue')
          AND c.conname LIKE '%experiential%'
    LOOP
        EXECUTE format(
            'ALTER TABLE %I RENAME CONSTRAINT %I TO %I',
            r.relname, r.conname,
            replace(r.conname, 'experiential', 'procedural'));
    END LOOP;
END $$;
"""

_REVERSE_RENAME_INDEXES_SQL = _RENAME_INDEXES_SQL.replace(
    "LIKE '%experiential%'", "LIKE '%procedural%'"
).replace(
    "replace(r.indexname, 'experiential', 'procedural')",
    "replace(r.indexname, 'procedural', 'experiential')",
)

# NOTE: the reverse scans keep the *procedural* table-name filter — at
# the point in downgrade() where they run, the tables have not been
# renamed back yet.
_REVERSE_RENAME_CONSTRAINTS_SQL = _RENAME_CONSTRAINTS_SQL.replace(
    "LIKE '%experiential%'", "LIKE '%procedural%'"
).replace(
    "replace(r.conname, 'experiential', 'procedural')",
    "replace(r.conname, 'procedural', 'experiential')",
)


def upgrade() -> None:
    conn = op.get_bind()

    # ------------------------------------------------------------------
    # Part A — rename the plane to *procedural*.
    # ------------------------------------------------------------------
    for old, new in _TABLE_RENAMES:
        op.rename_table(old, new)
    conn.execute(sa.text(_RENAME_INDEXES_SQL))
    conn.execute(sa.text(_RENAME_CONSTRAINTS_SQL))
    conn.execute(
        sa.text(
            'ALTER FUNCTION memex_experiential_tags_to_text(text[]) '
            'RENAME TO memex_procedural_tags_to_text'
        )
    )
    # Rename + heal the policy: dev DBs that ran 063 before the seed fix
    # carry the invalid {"hidden": true} blob (rejected by the typed
    # VaultPolicy, extra='forbid' — it raises in coerce_policy on every
    # reflect_enabled/summarize_enabled call). Reset to the §18.9.0
    # override {"reflect": true} (reflection ON, summary OFF). Idempotent
    # for fresh chains where 063 already seeds the correct blob.
    conn.execute(
        sa.text(
            "UPDATE vaults SET name = 'procedural', "
            "description = 'procedural memory plane (system vault).', "
            'policy = \'{"reflect": true}\'::jsonb '
            "WHERE name = 'experiential' AND kind = 'system'"
        )
    )

    # ------------------------------------------------------------------
    # Part B.1 — data conformance BEFORE constraint tightening.
    # ------------------------------------------------------------------
    # Cases leave the plane (FK CASCADE cleans versions/sources/pins).
    conn.execute(sa.text("DELETE FROM procedural_entries WHERE kind = 'case'"))

    # user-scoped rows → global where the anchor stays unique; delete the rest.
    conn.execute(
        sa.text(
            """
            UPDATE procedural_entries e
            SET scope = 'global'
            WHERE (e.scope = 'user' OR e.scope LIKE 'user:%')
              AND NOT EXISTS (
                SELECT 1 FROM procedural_entries g
                WHERE g.kind = e.kind
                  AND g.scope = 'global'
                  AND g.verb IS NOT DISTINCT FROM e.verb
                  AND g.context IS NOT DISTINCT FROM e.context
              )
            """
        )
    )
    conn.execute(
        sa.text("DELETE FROM procedural_entries WHERE scope = 'user' OR scope LIKE 'user:%'")
    )
    conn.execute(
        sa.text(
            "DELETE FROM procedural_pins WHERE context_key = 'user' OR context_key LIKE 'user:%'"
        )
    )

    # Strategy anchor: (scope, verb, NULL). NULL the context where unique;
    # delete collisions.
    conn.execute(
        sa.text(
            """
            UPDATE procedural_entries e
            SET context = NULL
            WHERE e.kind = 'strategy'
              AND e.context IS NOT NULL
              AND NOT EXISTS (
                SELECT 1 FROM procedural_entries s
                WHERE s.kind = 'strategy'
                  AND s.scope = e.scope
                  AND s.verb IS NOT DISTINCT FROM e.verb
                  AND s.context IS NULL
                  AND s.id <> e.id
              )
            """
        )
    )
    conn.execute(
        sa.text("DELETE FROM procedural_entries WHERE kind = 'strategy' AND context IS NOT NULL")
    )

    # Procedure anchor: verb AND context required.
    conn.execute(
        sa.text(
            'DELETE FROM procedural_entries '
            "WHERE kind = 'procedure' AND (verb IS NULL OR context IS NULL)"
        )
    )

    # ------------------------------------------------------------------
    # Part B.2 — constraint swap.
    # ------------------------------------------------------------------
    op.drop_constraint('ck_procedural_kind', 'procedural_entries', type_='check')
    op.create_check_constraint(
        'ck_procedural_kind',
        'procedural_entries',
        "kind IN ('procedure', 'strategy')",
    )

    op.drop_constraint('ck_strategy_context', 'procedural_entries', type_='check')
    op.create_check_constraint(
        'ck_strategy_anchor',
        'procedural_entries',
        "kind <> 'strategy' OR (verb IS NOT NULL AND context IS NULL)",
    )
    op.create_check_constraint(
        'ck_procedure_anchor',
        'procedural_entries',
        "kind <> 'procedure' OR (verb IS NOT NULL AND context IS NOT NULL)",
    )

    # Derivation-queue strategy constraint was backwards (required
    # target_context), making strategy derivations impossible to enqueue.
    # Swap to match the entries-table anchor: strategy ≡ (scope, verb),
    # context FORBIDDEN.
    op.drop_constraint(
        'ck_derivation_queue_strategy_context', 'procedural_derivation_queue', type_='check'
    )
    op.create_check_constraint(
        'ck_derivation_queue_strategy_anchor',
        'procedural_derivation_queue',
        "target_kind <> 'strategy' OR (target_verb IS NOT NULL AND target_context IS NULL)",
    )

    # One pin per (context, entry) — the old unique included `position`,
    # which let the same entry be pinned twice into a context (duplicate
    # briefing cards, burned budget). Drop any duplicate (context, entry)
    # pins keeping the lowest position, then swap the constraint.
    op.execute(
        """
        DELETE FROM procedural_pins p
        USING procedural_pins q
        WHERE p.context_key = q.context_key
          AND p.entry_id = q.entry_id
          AND p.position > q.position
        """
    )
    op.drop_constraint('uq_procedural_pins_chain_position', 'procedural_pins', type_='unique')
    op.create_unique_constraint(
        'uq_procedural_pins_context_entry',
        'procedural_pins',
        ['context_key', 'entry_id'],
    )

    # ------------------------------------------------------------------
    # Part B.3 — drop body_embedding (one retrieval embedding: the trigger).
    # ------------------------------------------------------------------
    op.drop_index(
        'idx_procedural_entries_body_embedding',
        table_name='procedural_entries',
        if_exists=True,
    )
    op.drop_constraint('ck_procedural_body_embedding_scope', 'procedural_entries', type_='check')
    op.drop_column('procedural_entries', 'body_embedding')

    op.drop_index(
        'idx_procedural_entries_trigger_embedding',
        table_name='procedural_entries',
        if_exists=True,
    )
    op.create_index(
        'idx_procedural_entries_trigger_embedding',
        'procedural_entries',
        ['trigger_embedding'],
        postgresql_using='hnsw',
        postgresql_ops={'trigger_embedding': 'vector_cosine_ops'},
        postgresql_where=sa.text("status = 'published'"),
    )

    # ------------------------------------------------------------------
    # Part B.4 — rebuild the generated tsvector to include the trigger.
    # ------------------------------------------------------------------
    op.drop_index(
        'idx_procedural_entries_search_tsvector',
        table_name='procedural_entries',
        if_exists=True,
    )
    op.drop_column('procedural_entries', 'search_tsvector')
    op.add_column(
        'procedural_entries',
        sa.Column(
            'search_tsvector',
            postgresql.TSVECTOR(),
            sa.Computed(_NEW_TSVECTOR_SQL, persisted=True),
        ),
    )
    op.create_index(
        'idx_procedural_entries_search_tsvector',
        'procedural_entries',
        ['search_tsvector'],
        postgresql_using='gin',
    )


def downgrade() -> None:
    conn = op.get_bind()

    # Reverse B.4 — old tsvector (needs the old function name first; do
    # the function rename early so the computed column can reference it).
    conn.execute(
        sa.text(
            'ALTER FUNCTION memex_procedural_tags_to_text(text[]) '
            'RENAME TO memex_experiential_tags_to_text'
        )
    )
    op.drop_index(
        'idx_procedural_entries_search_tsvector',
        table_name='procedural_entries',
        if_exists=True,
    )
    op.drop_column('procedural_entries', 'search_tsvector')
    op.add_column(
        'procedural_entries',
        sa.Column(
            'search_tsvector',
            postgresql.TSVECTOR(),
            sa.Computed(_OLD_TSVECTOR_SQL, persisted=True),
        ),
    )
    op.create_index(
        'idx_procedural_entries_search_tsvector',
        'procedural_entries',
        ['search_tsvector'],
        postgresql_using='gin',
    )

    # Reverse B.3 — body_embedding + old trigger index predicate.
    op.drop_index(
        'idx_procedural_entries_trigger_embedding',
        table_name='procedural_entries',
        if_exists=True,
    )
    op.create_index(
        'idx_procedural_entries_trigger_embedding',
        'procedural_entries',
        ['trigger_embedding'],
        postgresql_using='hnsw',
        postgresql_ops={'trigger_embedding': 'vector_cosine_ops'},
        postgresql_where=sa.text("status = 'published' AND kind = 'case'"),
    )

    from pgvector.sqlalchemy import Vector

    op.add_column(
        'procedural_entries',
        sa.Column('body_embedding', Vector(384), nullable=True),
    )
    op.create_check_constraint(
        'ck_procedural_body_embedding_scope',
        'procedural_entries',
        "(body_embedding IS NULL) OR (kind IN ('procedure', 'strategy'))",
    )
    op.create_index(
        'idx_procedural_entries_body_embedding',
        'procedural_entries',
        ['body_embedding'],
        postgresql_using='hnsw',
        postgresql_ops={'body_embedding': 'vector_cosine_ops'},
        postgresql_where=sa.text("status = 'published' AND kind IN ('procedure', 'strategy')"),
    )

    # Reverse the pin + derivation-queue constraint swaps.
    op.drop_constraint('uq_procedural_pins_context_entry', 'procedural_pins', type_='unique')
    op.create_unique_constraint(
        'uq_procedural_pins_chain_position',
        'procedural_pins',
        ['context_key', 'entry_id', 'position'],
    )
    op.drop_constraint(
        'ck_derivation_queue_strategy_anchor', 'procedural_derivation_queue', type_='check'
    )
    op.create_check_constraint(
        'ck_derivation_queue_strategy_context',
        'procedural_derivation_queue',
        "target_kind <> 'strategy' OR (target_verb IS NOT NULL AND target_context IS NOT NULL)",
    )

    # Reverse B.2 — old constraint set.
    op.drop_constraint('ck_procedure_anchor', 'procedural_entries', type_='check')
    op.drop_constraint('ck_strategy_anchor', 'procedural_entries', type_='check')
    op.create_check_constraint(
        'ck_strategy_context',
        'procedural_entries',
        "kind <> 'strategy' OR (verb IS NOT NULL AND context IS NOT NULL)",
    )
    op.drop_constraint('ck_procedural_kind', 'procedural_entries', type_='check')
    op.create_check_constraint(
        'ck_procedural_kind',
        'procedural_entries',
        "kind IN ('case', 'procedure', 'strategy')",
    )

    # Reverse A — names back to experiential.
    conn.execute(
        sa.text(
            "UPDATE vaults SET name = 'experiential', "
            "description = 'procedural & experiential memory plane (system vault).' "
            "WHERE name = 'procedural' AND kind = 'system'"
        )
    )
    conn.execute(sa.text(_REVERSE_RENAME_INDEXES_SQL))
    conn.execute(sa.text(_REVERSE_RENAME_CONSTRAINTS_SQL))
    for old, new in _TABLE_RENAMES:
        op.rename_table(new, old)
