"""Alembic async migration environment for Memex.

Supports:
- Async SQLAlchemy engine (asyncpg)
- SQLModel metadata (pgvector Vector columns)
- Advisory locking to prevent concurrent migration races
- pgvector autogenerate (render_item / compare_type)
"""

import asyncio
import logging
from logging.config import fileConfig

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import pool, text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel import SQLModel

# Import all models so SQLModel.metadata is fully populated.
import memex_core.memory.sql_models  # noqa: F401
from memex_core.storage.db_url import get_database_url

logger = logging.getLogger('alembic.env')

# Alembic Config object — provides access to alembic.ini values.
config = context.config

# Interpret the config file for Python logging (if present).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The metadata object used for autogenerate support.
target_metadata = SQLModel.metadata

# Advisory lock ID used to serialize migrations across workers.
MIGRATION_LOCK_ID = 720_701


# ---------------------------------------------------------------------------
# pgvector autogenerate helpers
# ---------------------------------------------------------------------------


def include_object(object, name, type_, reflected, compare_to):
    """Skip the alembic_version table during autogenerate."""
    if type_ == 'table' and name == 'alembic_version':
        return False
    return True


def render_item(type_, obj, autogen_context):
    """Render Vector columns correctly in autogenerated migrations."""
    if type_ == 'type' and isinstance(obj, Vector):
        autogen_context.imports.add('from pgvector.sqlalchemy import Vector')
        return f'Vector({obj.dim})'
    return False


def compare_type(context, inspected_column, metadata_column, inspected_type, metadata_type):
    """Prevent false positives for Vector columns (reflected as USER-DEFINED)."""
    if isinstance(metadata_type, Vector):
        return False
    return None


def _resolve_url() -> str:
    """Resolve the database URL, with alembic.ini as final fallback."""
    try:
        return get_database_url()
    except RuntimeError:
        ini_url = config.get_main_option('sqlalchemy.url')
        if ini_url:
            return ini_url
        raise


_AUTOGEN_KWARGS = {
    'include_object': include_object,
    'render_item': render_item,
    'compare_type': compare_type,
}


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL to stdout.

    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well. By skipping engine
    creation we don't even need a DBAPI to be available.
    """
    url = _resolve_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={'paramstyle': 'named'},
        **_AUTOGEN_KWARGS,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    """Run migrations with an active connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        **_AUTOGEN_KWARGS,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode with an async engine.

    Acquires a PostgreSQL advisory lock first to prevent concurrent
    migration execution across multiple workers.
    """
    connectable = create_async_engine(
        _resolve_url(),
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        # Acquire advisory lock to serialize migrations
        await connection.execute(text(f'SELECT pg_advisory_lock({MIGRATION_LOCK_ID})'))
        try:
            await connection.run_sync(do_run_migrations)
        finally:
            # Rollback any aborted transaction so the unlock can succeed.
            try:
                await connection.rollback()
            except Exception:
                pass
            try:
                await connection.execute(text(f'SELECT pg_advisory_unlock({MIGRATION_LOCK_ID})'))
            except Exception:
                logger.warning('Failed to release advisory lock %s', MIGRATION_LOCK_ID)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online migrations — delegates to async runner."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
