"""Alembic async migration environment for Memex.

Supports:
- Synchronous SQLAlchemy engine (psycopg v3) — alembic is sync; the runtime app
  uses asyncpg, but migrations swap to psycopg so multi-statement op.execute()
  blocks work (see ``_sync_url``).
- SQLModel metadata (pgvector Vector columns)
- Advisory locking to prevent concurrent migration races
- pgvector autogenerate (render_item / compare_type)
"""

import logging
from logging.config import fileConfig

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import pool, text
from sqlmodel import SQLModel

# Import all models so SQLModel.metadata is fully populated.
import memex_core.memory.sql_models  # noqa: F401
from memex_core.storage.db_url import get_database_url

logger = logging.getLogger('alembic.env')

# Alembic Config object — provides access to alembic.ini values.
config = context.config

# Interpret the config file for Python logging (if present).
# disable_existing_loggers=False is required so we don't disable every
# logger created before this point. The default (True) would mark
# every already-instantiated logger (memex_eval.*, structlog-bridged, etc.)
# as ``disabled=True``, which silently swallows their records for the rest
# of the process — including any ``caplog`` capture in tests.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# The metadata object used for autogenerate support.
target_metadata = SQLModel.metadata

# Advisory lock ID used to serialize migrations across workers.
MIGRATION_LOCK_ID = 720_701


# ---------------------------------------------------------------------------
# pgvector autogenerate helpers
# ---------------------------------------------------------------------------


def include_object(object, name, type_, reflected, compare_to):
    """Skip the alembic_version table during autogenerate."""
    if type_ == 'table' and name == 'alembic_version':
        return False
    return True


def render_item(type_, obj, autogen_context):
    """Render Vector columns correctly in autogenerated migrations."""
    if type_ == 'type' and isinstance(obj, Vector):
        autogen_context.imports.add('from pgvector.sqlalchemy import Vector')
        return f'Vector({obj.dim})'
    return False


def compare_type(context, inspected_column, metadata_column, inspected_type, metadata_type):
    """Prevent false positives for Vector columns (reflected as USER-DEFINED)."""
    if isinstance(metadata_type, Vector):
        return False
    return None


def _resolve_url() -> str:
    """Resolve the database URL, with alembic.ini as final fallback."""
    try:
        return get_database_url()
    except RuntimeError:
        ini_url = config.get_main_option('sqlalchemy.url')
        if ini_url:
            return ini_url
        raise


_AUTOGEN_KWARGS = {
    'include_object': include_object,
    'render_item': render_item,
    'compare_type': compare_type,
}


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL to stdout.

    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well. By skipping engine
    creation we don't even need a DBAPI to be available.
    """
    url = _resolve_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={'paramstyle': 'named'},
        **_AUTOGEN_KWARGS,
    )

    with context.begin_transaction():
        context.run_migrations()


def _is_fresh_db(connection) -> bool:
    """True when the public schema has zero application tables."""
    result = connection.execute(
        text(
            'SELECT NOT EXISTS ('
            '  SELECT 1 FROM information_schema.tables'
            "  WHERE table_schema = 'public' AND table_name = 'vaults'"
            ')'
        )
    )
    return bool(result.scalar())


def _bootstrap_fresh_db(connection) -> None:
    """Fast-path for a brand-new database.

    ``SQLModel.metadata.create_all`` builds every table from the current
    Python model definitions — including columns added by later
    migrations. Running the migration chain after that would fail on
    every ``ALTER TABLE ADD COLUMN`` because the column already exists.

    Instead: create everything in one shot, stamp alembic at HEAD, done.
    Data-carrying migrations (backfills) are no-ops on an empty DB.
    """
    connection.execute(text('CREATE EXTENSION IF NOT EXISTS vector'))
    connection.execute(text('CREATE EXTENSION IF NOT EXISTS pg_trgm'))
    SQLModel.metadata.create_all(bind=connection)

    script_dir = context.script
    head = script_dir.get_current_head()
    connection.execute(
        text(
            'CREATE TABLE IF NOT EXISTS alembic_version ('
            '  version_num VARCHAR(128) NOT NULL,'
            '  CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)'
            ')'
        )
    )
    connection.execute(text('DELETE FROM alembic_version'))
    connection.execute(
        text('INSERT INTO alembic_version (version_num) VALUES (:rev)'),
        {'rev': head},
    )
    logger.info('Fresh database: created all tables via create_all, stamped at %s', head)


def do_run_migrations(connection):
    """Run migrations with an active connection.

    On a fresh database (no application tables), takes a shortcut:
    ``create_all`` + stamp HEAD. On an existing database, runs the
    normal alembic migration chain.

    When migrating to HEAD, ``create_all`` runs as the final step
    (idempotent via ``checkfirst``) so SQLModel classes added since the DB's
    last ``create_all`` exist without manual intervention.

    Both shortcuts are gated on the destination being HEAD. A TARGETED
    migration (``upgrade <rev>`` / ``downgrade <rev>`` — only tests do this)
    must run the real chain step by step and leave the schema exactly at that
    revision: the fresh-DB create_all+stamp-HEAD fast-path would jump straight
    to HEAD, and a trailing ``create_all`` would both add HEAD-only columns to
    an earlier revision AND re-create tables a downgrade just dropped.
    """
    try:
        target = context.get_revision_argument()
    except Exception:
        target = None
    to_head = target is None or target in ('head', 'heads')

    if _is_fresh_db(connection):
        if to_head:
            _bootstrap_fresh_db(connection)
            return
        # Fresh DB + targeted upgrade: run the real chain from base. alembic
        # creates alembic_version itself; don't widen a table that's absent.
    else:
        # Widen alembic_version.version_num if it's still the default
        # varchar(32) — revision ids can exceed 32 chars.
        connection.execute(
            text('ALTER TABLE alembic_version ALTER COLUMN version_num TYPE varchar(128)')
        )

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        **_AUTOGEN_KWARGS,
    )
    with context.begin_transaction():
        context.run_migrations()

    if to_head:
        SQLModel.metadata.create_all(bind=connection, checkfirst=True)


def _sync_url(url: str) -> str:
    """Convert the runtime asyncpg URL to its synchronous psycopg (v3) sibling.

    Alembic is synchronous and is not designed to run under an async driver.
    asyncpg sends every statement over the extended query protocol as a
    prepared statement, and Postgres forbids more than one command per
    prepared statement — so a migration that batches multiple statements in a
    single ``op.execute()`` (an idiom used across the migration history)
    raises ``cannot insert multiple commands into a prepared statement``.
    psycopg (v3) executes such parameterless multi-statement blocks fine.
    The runtime app keeps using asyncpg — only the migration engine swaps
    drivers.
    """
    prefix = 'postgresql+asyncpg://'
    if url.startswith(prefix):
        return 'postgresql+psycopg://' + url[len(prefix) :]
    return url


def run_migrations_online() -> None:
    """Run migrations in 'online' mode with a synchronous (psycopg2) engine.

    Acquires a PostgreSQL advisory lock first to prevent concurrent
    migration execution across multiple workers.
    """
    from sqlalchemy import create_engine

    connectable = create_engine(
        _sync_url(_resolve_url()),
        poolclass=pool.NullPool,
    )
    try:
        with connectable.connect() as connection:
            # Session-level advisory lock to serialize migrations; released
            # when the connection closes.
            connection.execute(text(f'SELECT pg_advisory_lock({MIGRATION_LOCK_ID})'))
            do_run_migrations(connection)
            # do_run_migrations opens its own transaction(s) via
            # context.begin_transaction(); commit the outer connection so the
            # advisory-lock session and any DDL run outside that block persist.
            connection.commit()
    finally:
        connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
