"""Custom models for Memex used internally for note management and retrieval."""

import datetime as dt
from enum import Enum
from typing import Any, Annotated
from uuid import UUID
from pydantic import (
    BaseModel,
    Field,
    PrivateAttr,
    field_serializer,
    BeforeValidator,
    ConfigDict,
    model_validator,
)
import base64

from memex_common.types import MemexTypes, FactTypes
from memex_common.mixins import VaultMixin


def decode_base64(v: Any) -> bytes:
    """Validate and return Base64 encoded bytes."""
    if isinstance(v, str):
        v = v.encode('utf-8')

    if isinstance(v, bytes):
        try:
            # Check if it is valid base64 by trying to decode it
            # We don't return the decoded value, we return the original v
            base64.b64decode(v, validate=True)
            return v
        except Exception as e:
            raise ValueError(f'Value is not valid Base64 encoded data: {e}')
    return v


Base64Bytes = Annotated[bytes, BeforeValidator(decode_base64)]


class LineageDirection(str, Enum):
    """Direction of lineage traversal."""

    UPSTREAM = 'upstream'
    DOWNSTREAM = 'downstream'
    BOTH = 'both'


class LineageResponse(BaseModel):
    """Recursive schema for lineage response."""

    entity_type: str = Field(description='The type of the entity (mental_model, observation, etc.)')
    entity: dict[str, Any] = Field(description='The full DTO of the entity.')
    derived_from: list['LineageResponse'] = Field(
        default_factory=list,
        description='List of entities this entity is derived from (upstream) or that are derived from it (downstream).',
    )


LineageResponse.model_rebuild()


class NoteMetadata(BaseModel):
    """A markdown note stored in the file system. Can be generated by the user or an LLM."""

    # NB: may need to be moved
    _manifest_path: str | None = PrivateAttr(default=None)

    date_created: dt.datetime = Field(
        default_factory=lambda: dt.datetime.now(dt.timezone.utc),
        description='The timestamp when the note was created',
    )

    ## These fields can be updated **after** the note metadata is initialized
    uuid: str | None = Field(
        default=None,
        description='The unique identifier of the note (all files in the note share this UUID)',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    name: str | None = Field(
        default=None, description='The name of the note', examples=['helpful-assistant']
    )
    files: list[str] | None = Field(
        default=None,
        description='List of files associated with the note',
        examples=[
            ['ROLE.md'],
            ['skills/helpful-assistant/SKILL.md', 'skills/helpful-assistant/scripts/utils.py'],
        ],
    )
    description: str | None = Field(
        default=None,
        description='A summary of the entire note, answering Who, What, When, Where, Why, How',
        examples=['A helpful role that assists users in managing tasks.'],
    )
    author: str | None = Field(
        default=None,
        description='Name of the author who created the entity.',
        examples=['user', 'claude opus', 'gemini 3'],
    )
    project: str | None = Field(
        default=None,
        description='Optional project name associated with the entity.',
        examples=['infrastructure migration', 'memex'],
    )
    etag: str | None = Field(
        default=None,
        description="The MD5 hash of the note's description file (e.g. NOTE.md)",
        examples=['9e107d9d372bb6826bd81d3542a419d6'],
    )
    tags: list[str] | None = Field(
        default=None,
        description='List of tags associated with the note',
        examples=[['assistant', 'helpful', 'task-management']],
    )
    embedding: list[float] | None = Field(
        default=None,
        description='The embedding vector representing the note for similarity searches',
    )
    type: MemexTypes | None = Field(
        default=None,
        description='The type of the Memex entity',
    )

    # NB: this needs to be done because IndexEntry types can be string or None
    def model_post_init(self, __context) -> None:
        # Mypy complains
        self.type: str | None
        if self.type is None:
            self.type = MemexTypes.NOTE

    @field_serializer('type')
    def serialize_type(self, type: MemexTypes | None) -> str | None:
        if type is None:
            return None
        else:
            return type.value

    @field_serializer('date_created')
    def serialize_date_created(self, date_created: dt.datetime) -> str:
        return date_created.isoformat()

    def update(self, key: str, value: list[float] | list[str] | str | None):
        setattr(self, key, value)


class RetainContent(VaultMixin):
    """Input context for content retention."""

    content: str = Field(..., description='The content to be retained.')
    event_date: dt.datetime = Field(
        default_factory=lambda: dt.datetime.now(tz=dt.timezone.utc),
        description='The date of when the content was created or relevant.',
    )
    context: str | None = Field(default=None, description='Additional context for the content.')
    payload: dict[str, Any] = Field(
        default_factory=dict, description='Additional metadata for the content.'
    )


class RetrievalRequest(BaseModel):
    """
    Unified request object for memory retrieval.
    """

    query: str = Field(..., description='The search query or context string.')
    limit: int = Field(default=10, description='Maximum number of results to return.')
    offset: int = Field(default=0, description='Number of results to skip.')
    token_budget: int | None = Field(
        default=None, description='Maximum token budget for results (greedy packing).'
    )

    # Scoping
    vault_ids: list[UUID | str] | None = Field(
        default=None,
        description='List of specific vault IDs or names to search. If None or empty, searches ALL vaults.',
    )
    filters: dict[str, Any] = Field(
        default_factory=dict, description='Optional key-value filters (e.g. fact_type).'
    )

    # Advanced options
    rerank: bool = Field(
        default=True, description='Whether to apply neural reranking if available.'
    )
    min_score: float | None = Field(
        default=None, description='Minimum score threshold for results (post-reranking).'
    )
    strategy_weights: dict[str, float] | None = Field(
        default=None, description='Optional custom weights for RRF fusion.'
    )
    strategies: list[str] | None = Field(
        default=None,
        description=(
            'Inclusion list of strategies to run. '
            'Valid values: semantic, keyword, graph, temporal, mental_model. '
            'If None, all strategies are used.'
        ),
    )
    include_vectors: bool = Field(
        default=False, description='Whether to include embeddings in the result (slower).'
    )
    include_stale: bool = Field(
        default=False, description='Whether to include stale memory units in results.'
    )
    skip_opinion_formation: bool = Field(
        default=False, description='Whether to skip the automated opinion formation loop.'
    )


class ReflectionRequest(VaultMixin):
    """
    Request to run the reflection loop on a specific entity.
    """

    entity_id: UUID = Field(description='The UUID of the entity to reflect upon.')
    limit_recent_memories: int = Field(
        default=20, description='Number of recent memories to consider.'
    )


class OpinionFormationRequest(VaultMixin):
    """
    Request to form opinions based on an interaction.
    """

    query: str = Field(description="The user's original query.")
    # In common, we use a simpler representation of MemoryUnit if possible
    # or just use dict if we don't want to pull in MemoryUnit SQLModel.
    context: list[dict[str, Any]] = Field(
        description='Optional structured context with memory unit data.'
    )
    answer: str = Field(description="The agent's final answer.")
    agent_name: str = Field(default='reasoning_agent', description='The identity of the agent.')


class IngestURLRequest(VaultMixin):
    """Request to ingest content from a URL."""

    url: str = Field(..., description='The URL to ingest.')
    reflect_after: bool = Field(
        default=True, description='Whether to run reflection after ingestion.'
    )
    assets: dict[str, str] = Field(
        default_factory=dict,
        description='Optional dictionary of assets (filename -> base64 content).',
    )


class IngestFileRequest(VaultMixin):
    """Request to ingest content from a local file path (server-side)."""

    file_path: str = Field(..., description='The absolute path to the file on the server.')
    reflect_after: bool = Field(
        default=True, description='Whether to run reflection after ingestion.'
    )


class AdjustBeliefRequest(BaseModel):
    """Request to adjust belief confidence."""

    unit_uuid: UUID = Field(..., description='The UUID of the memory unit.')
    evidence_type_key: str = Field(..., description='The type of evidence (e.g. "confirm").')
    description: str | None = Field(default=None, description='Optional explanation.')


class CreateVaultRequest(BaseModel):
    """Request to create a new vault."""

    name: str = Field(..., description='The name of the vault.')

    description: str | None = Field(default=None, description='Optional description.')


class MemoryUnitBase(VaultMixin):
    """Base schema for Memory Unit shared between DTOs and SQLModels."""

    text: str = Field(description='The textual content of the memory unit.')
    fact_type: FactTypes = Field(description='The type/category of the memory unit.')
    status: str = Field(
        default='active',
        description='Content status: active or stale.',
        examples=['active', 'stale'],
    )

    mentioned_at: dt.datetime | None = Field(
        default=None, description='The datetime when the memory unit was mentioned.'
    )
    occurred_start: dt.datetime | None = Field(
        default=None, description='The start datetime of when the fact/event occurred.'
    )
    occurred_end: dt.datetime | None = Field(
        default=None, description='The end datetime of when the fact/event occurred.'
    )


class MemoryUnitDTO(MemoryUnitBase):
    """DTO for a Memory Unit (Fact/Experience)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(
        description='The unique identifier of the memory unit.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    note_id: UUID | None = Field(
        default=None,
        description='The unique identifier of the source note.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    source_note_ids: list[UUID] = Field(
        default_factory=list,
        description='List of source note IDs. For facts, typically single. For opinions, derived from evidence.',
        examples=[['123e4567-e89b-12d3-a456-426614174000']],
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description='Additional metadata associated with the memory unit.',
        examples=[{'source': 'interview', 'author': 'user'}],
    )

    score: float | None = Field(
        default=None,
        description='Relevance score from retrieval or reranking (0.0 to 1.0).',
        examples=[0.95],
    )


class ObservationDTO(BaseModel):
    """DTO for an Observation (Mental Model component)."""

    id: UUID | None = Field(
        default=None,
        description='The unique identifier of the observation.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    title: str = Field(
        description='Short title or headline for the observation.',
        examples=['User prefers Python over Java'],
    )

    content: str = Field(
        description='Detailed content of the observation.',
        examples=['The user consistently chooses Python for new projects due to its simplicity.'],
    )

    trend: str | None = Field(
        default=None,
        description='Current trend of this observation (e.g. new, stable, strengthening).',
        examples=['strengthening'],
    )

    evidence: list[dict[str, Any]] = Field(
        default_factory=list,
        description='List of supporting evidence items.',
        examples=[{'memory_id': '...', 'quote': 'I love Python'}],
    )


class EntityDTO(BaseModel):
    """DTO for an Entity."""

    id: UUID = Field(
        description='The unique identifier of the entity.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    name: str = Field(
        description='The canonical name of the entity.',
        examples=['Python'],
    )

    mention_count: int = Field(
        default=0,
        description='Cumulative number of times this entity has been mentioned.',
        examples=[42],
    )

    vault_id: UUID | None = Field(
        default=None,
        description='The UUID of the vault this entity belongs to.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )


class VaultDTO(BaseModel):
    """DTO for a Vault."""

    id: UUID = Field(
        description='The unique identifier of the vault.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    name: str = Field(
        description='The name of the vault.',
        examples=['Personal', 'Work'],
    )

    description: str | None = Field(
        default=None,
        description='Optional description of the vault.',
        examples=['My personal memories and notes.'],
    )


class DefaultVaultsResponse(BaseModel):
    """Response model for the default vaults endpoint."""

    active_vault: VaultDTO = Field(
        description='The active (writer) vault.',
    )
    attached_vaults: list[VaultDTO] = Field(
        default_factory=list,
        description='Additional read-only vaults included in search/retrieval.',
    )


class NoteCreateDTO(BaseModel):
    """DTO for creating a Note artifact (input/ingestion)."""

    name: str = Field(
        description='The name of the note.',
        examples=['Meeting Notes'],
    )
    note_key: str | None = Field(
        default=None,
        description='A unique stable key for the note to enable incremental updates.',
        examples=['my-stable-note-id'],
    )
    description: str = Field(
        description='A brief description or summary of the note.',
        examples=['Notes from the weekly team sync.'],
    )
    content: Base64Bytes = Field(
        description='Base64 encoded content of the note.',
        examples=['VGhpcyBpcyBhIHRlc3Qgbm90ZS4='],
    )
    files: dict[str, Base64Bytes] = Field(
        default_factory=dict,
        description='Dictionary mapping filenames to Base64 encoded content.',
        examples=[
            {
                'image.png': 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
            }
        ],
    )
    tags: list[str] = Field(
        default_factory=list,
        description='List of tags associated with the note.',
        examples=[['meeting', 'work']],
    )
    vault_id: str | UUID | None = Field(
        default=None,
        description='Optional target vault ID or name.',
    )

    @property
    def content_decoded(self) -> bytes:
        """Return the decoded raw bytes of the note content."""
        return base64.b64decode(self.content)

    @property
    def files_decoded(self) -> dict[str, bytes]:
        """Return a dictionary of filenames to decoded raw bytes."""
        return {k: base64.b64decode(v) for k, v in self.files.items()}

    @field_serializer('content')
    def serialize_content(self, content: bytes) -> str:
        return content.decode('utf-8')

    @field_serializer('files')
    def serialize_files(self, files: dict[str, bytes]) -> dict[str, str]:
        return {k: v.decode('utf-8') for k, v in files.items()}


class IngestResponse(BaseModel):
    """Response from ingestion."""

    status: str = Field(
        description='Status of the ingestion operation.',
        examples=['success', 'skipped', 'failed'],
    )

    note_id: str | None = Field(
        default=None,
        description='The unique identifier of the ingested note.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    unit_ids: list[UUID] = Field(
        default_factory=list,
        description='List of UUIDs for the extracted memory units.',
        examples=[['123e4567-e89b-12d3-a456-426614174001', '123e4567-e89b-12d3-a456-426614174002']],
    )

    reason: str | None = Field(
        default=None,
        description='Reason for skipping or failure, if applicable.',
        examples=['idempotency_check'],
    )


class ReflectionResultDTO(BaseModel):
    """DTO for reflection results."""

    entity_id: UUID = Field(
        description='The UUID of the entity reflected upon.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    new_observations: list[ObservationDTO] = Field(
        description='List of new observations generated during reflection.',
    )

    status: str = Field(
        default='success',
        description='Status of the reflection operation.',
        examples=['success', 'failed'],
    )


class ReflectionQueueDTO(BaseModel):
    """DTO for reflection queue item."""

    entity_id: UUID = Field(
        description='The UUID of the entity in the queue.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    vault_id: UUID = Field(
        description='The UUID of the vault associated with the entity.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    priority_score: float = Field(
        default=0.0,
        description='Priority score for processing.',
        examples=[0.85],
    )


class BatchIngestRequest(BaseModel):
    """Request for batch ingestion of notes."""

    notes: list[NoteCreateDTO] = Field(..., description='List of notes to ingest.')
    vault_id: UUID | str | None = Field(
        default=None,
        description='Optional target vault ID or name that overrides note-level vault.',
    )
    batch_size: int = Field(default=32, description='Internal processing chunk size.', ge=1, le=100)


class BatchIngestResponse(BaseModel):
    """Final response from a batch ingestion operation."""

    processed_count: int = Field(default=0, description='Number of successfully processed notes.')
    skipped_count: int = Field(default=0, description='Number of skipped notes (e.g. duplicates).')
    failed_count: int = Field(default=0, description='Number of notes that failed to process.')
    note_ids: list[str] = Field(default_factory=list, description='List of created Note UUIDs.')
    errors: list[dict[str, Any]] = Field(
        default_factory=list, description='Detailed error information indexed by input.'
    )


class BatchJobStatus(BaseModel):
    """Current status of an asynchronous batch job."""

    job_id: UUID = Field(..., description='The unique identifier of the batch job.')
    status: str = Field(
        ...,
        description='Current status of the job.',
        examples=['pending', 'processing', 'completed', 'failed'],
    )
    progress: str | None = Field(default=None, description='Optional human-readable progress info.')
    result: BatchIngestResponse | None = Field(
        default=None, description='Final results, available when status is "completed".'
    )


class SystemStatsCountsDTO(BaseModel):
    """Counts for system entities."""

    memories: int = Field(description='Total number of memories (Documents).')
    entities: int = Field(description='Total number of entities.')
    reflection_queue: int = Field(description='Number of items in the reflection queue.')


class TokenUsageStatDTO(BaseModel):
    """Token usage for a specific date."""

    date: dt.date
    total_tokens: int


class TokenUsageResponse(BaseModel):
    """Daily aggregated token usage response."""

    usage: list[TokenUsageStatDTO]


class NodeDTO(BaseModel):
    """DTO for a note node (section produced by PageIndex)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    note_id: UUID
    vault_id: UUID
    title: str
    text: str
    level: int
    seq: int
    status: str
    created_at: dt.datetime


class NoteDTO(BaseModel):
    """DTO for a Note (output/retrieval)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    title: str | None = None
    name: str | None = None
    original_text: str | None = None
    created_at: dt.datetime
    vault_id: UUID
    assets: list[str] = Field(default_factory=list)
    doc_metadata: dict[str, Any] = Field(default_factory=dict)


class NoteSnippet(BaseModel):
    """Snippet of text from a note."""

    text: str
    score: float = 0.0
    chunk_index: int | None = None
    # Legacy fields (optional)
    id: UUID | None = None
    fact_type: FactTypes | str | None = None
    event_date: str | None = None
    # Node-level info (populated when PageIndex strategy was used)
    node_id: UUID | None = None
    node_title: str | None = None
    node_level: int | None = None


class NoteSearchResult(BaseModel):
    """Result of a note search."""

    note_id: UUID
    metadata: dict[str, Any]
    snippets: list[NoteSnippet]
    score: float = 0.0
    reasoning: list[dict[str, Any]] | None = Field(
        default=None,
        description='Identified sections with reasoning text and node IDs (populated when reason=True).',
    )
    answer: str | None = Field(
        default=None,
        description='LLM-generated answer when summarize=True.',
    )


class NoteSearchRequest(BaseModel):
    """Request to search for notes."""

    query: str
    limit: int = 10
    vault_ids: list[UUID | str] | None = None
    expand_query: bool = False
    fusion_strategy: str = 'rrf'
    strategies: list[str] = Field(default=['semantic', 'keyword', 'graph', 'temporal'])
    strategy_weights: dict[str, float] | None = Field(default=None)
    reason: bool = Field(
        default=False,
        description='Run skeleton-tree identification — returns reasoning + relevant section IDs.',
    )
    summarize: bool = Field(
        default=False,
        description='Synthesize a full answer from identified sections (implies reason=True).',
    )

    @model_validator(mode='after')
    def _ensure_reason_if_summarize(self) -> 'NoteSearchRequest':
        if self.summarize:
            self.reason = True
        return self


class SummaryRequest(BaseModel):
    """Request for AI-generated summary of search results."""

    query: str = Field(..., description='The original search query.')
    texts: list[str] = Field(
        ...,
        description='Search result texts to summarize.',
        max_length=50,
    )


class SummaryResponse(BaseModel):
    """Response containing an AI-generated summary with citations."""

    summary: str = Field(
        description='AI-generated summary with bracket citations (e.g. [0], [1]).',
    )
