"""Custom models for Memex used internally for note management and retrieval."""

import datetime as dt
from enum import Enum
from typing import Any, Annotated
from uuid import UUID
from pydantic import (
    BaseModel,
    Field,
    PrivateAttr,
    field_serializer,
    BeforeValidator,
    ConfigDict,
    model_validator,
)
import base64
import binascii

from memex_common.types import MemexTypes, FactTypes
from memex_common.mixins import VaultMixin


def decode_base64(v: Any) -> bytes:
    """Validate and return Base64 encoded bytes."""
    if isinstance(v, str):
        v = v.encode('utf-8')

    if isinstance(v, bytes):
        try:
            # Check if it is valid base64 by trying to decode it
            # We don't return the decoded value, we return the original v
            base64.b64decode(v, validate=True)
            return v
        except binascii.Error as e:
            raise ValueError(f'Value is not valid Base64 encoded data: {e}')
    return v


Base64Bytes = Annotated[bytes, BeforeValidator(decode_base64)]


class EntityType(str, Enum):
    """Semantic type of an entity in the knowledge graph."""

    PERSON = 'Person'
    ORGANIZATION = 'Organization'
    LOCATION = 'Location'
    CONCEPT = 'Concept'
    TECHNOLOGY = 'Technology'
    FILE = 'File'
    MISC = 'Misc'


class LineageDirection(str, Enum):
    """Direction of lineage traversal."""

    UPSTREAM = 'upstream'
    DOWNSTREAM = 'downstream'
    BOTH = 'both'


class LineageResponse(BaseModel):
    """Recursive schema for lineage response."""

    entity_type: str = Field(description='The type of the entity (mental_model, observation, etc.)')
    entity: dict[str, Any] = Field(description='The full DTO of the entity.')
    derived_from: list['LineageResponse'] = Field(
        default_factory=list,
        description='List of entities this entity is derived from (upstream) or that are derived from it (downstream).',
    )


LineageResponse.model_rebuild()


class NoteMetadata(BaseModel):
    """A markdown note stored in the file system. Can be generated by the user or an LLM."""

    # NB: may need to be moved
    _manifest_path: str | None = PrivateAttr(default=None)

    date_created: dt.datetime = Field(
        default_factory=lambda: dt.datetime.now(dt.timezone.utc),
        description='The timestamp when the note was created',
    )

    ## These fields can be updated **after** the note metadata is initialized
    uuid: str | None = Field(
        default=None,
        description='The unique identifier of the note (all files in the note share this UUID)',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    name: str | None = Field(
        default=None, description='The name of the note', examples=['helpful-assistant']
    )
    files: list[str] | None = Field(
        default=None,
        description='List of files associated with the note',
        examples=[
            ['ROLE.md'],
            ['skills/helpful-assistant/SKILL.md', 'skills/helpful-assistant/scripts/utils.py'],
        ],
    )
    description: str | None = Field(
        default=None,
        description='A summary of the entire note, answering Who, What, When, Where, Why, How',
        examples=['A helpful role that assists users in managing tasks.'],
    )
    author: str | None = Field(
        default=None,
        description='Name of the author who created the entity.',
        examples=['user', 'claude opus', 'gemini 3'],
    )
    etag: str | None = Field(
        default=None,
        description="The MD5 hash of the note's description file (e.g. NOTE.md)",
        examples=['9e107d9d372bb6826bd81d3542a419d6'],
    )
    tags: list[str] | None = Field(
        default=None,
        description='List of tags associated with the note',
        examples=[['assistant', 'helpful', 'task-management']],
    )
    type: MemexTypes | None = Field(
        default=None,
        description='The type of the Memex entity',
    )

    # NB: this needs to be done because IndexEntry types can be string or None
    def model_post_init(self, __context) -> None:
        # Mypy complains
        self.type: str | None
        if self.type is None:
            self.type = MemexTypes.NOTE

    @field_serializer('type')
    def serialize_type(self, type: MemexTypes | None) -> str | None:
        if type is None:
            return None
        else:
            return type.value

    @field_serializer('date_created')
    def serialize_date_created(self, date_created: dt.datetime) -> str:
        return date_created.isoformat()

    def update(self, key: str, value: list[float] | list[str] | str | None):
        setattr(self, key, value)


class RetainContent(VaultMixin):
    """Input context for content retention."""

    content: str = Field(..., description='The content to be retained.')
    event_date: dt.datetime = Field(
        default_factory=lambda: dt.datetime.now(tz=dt.timezone.utc),
        description='The date of when the content was created or relevant.',
    )
    context: str | None = Field(default=None, description='Additional context for the content.')
    payload: dict[str, Any] = Field(
        default_factory=dict, description='Additional metadata for the content.'
    )


class RetrievalRequest(BaseModel):
    """
    Unified request object for memory retrieval.
    """

    query: str = Field(..., description='The search query or context string.')
    limit: int = Field(default=10, description='Maximum number of results to return.')
    offset: int = Field(default=0, description='Number of results to skip.')
    token_budget: int | None = Field(
        default=None, description='Maximum token budget for results (greedy packing).'
    )

    # Scoping
    vault_ids: list[UUID | str] | None = Field(
        default=None,
        description='List of specific vault IDs or names to search. If None or empty, searches ALL vaults.',
    )
    filters: dict[str, Any] = Field(
        default_factory=dict, description='Optional key-value filters (e.g. fact_type).'
    )

    # Temporal filtering
    after: dt.datetime | None = Field(
        default=None, description='Only return results after this date (ISO 8601).'
    )
    before: dt.datetime | None = Field(
        default=None, description='Only return results before this date (ISO 8601).'
    )

    # Tag filtering
    tags: list[str] | None = Field(
        default=None, description='Only return results from notes with ALL of these tags.'
    )

    # Source context filtering
    source_context: str | None = Field(
        default=None,
        description=(
            'Filter MemoryUnits by their context field (e.g. "user_notes"). '
            'When set, only units with matching context are returned.'
        ),
    )

    # Advanced options
    rerank: bool = Field(
        default=True, description='Whether to apply neural reranking if available.'
    )
    min_score: float | None = Field(
        default=None, description='Minimum score threshold for results (post-reranking).'
    )
    strategy_weights: dict[str, float] | None = Field(
        default=None, description='Optional custom weights for RRF fusion.'
    )
    strategies: list[str] | None = Field(
        default=None,
        description=(
            'Inclusion list of strategies to run. '
            'Valid values: semantic, keyword, graph, temporal, mental_model. '
            'If None, all strategies are used.'
        ),
    )
    include_vectors: bool = Field(
        default=False, description='Whether to include embeddings in the result (slower).'
    )
    include_stale: bool = Field(
        default=False, description='Whether to include stale memory units in results.'
    )
    include_superseded: bool = Field(
        default=False,
        description='Whether to include superseded (low-confidence) memory units in results.',
    )
    debug: bool = Field(
        default=False,
        description=(
            'When True, include per-result strategy attribution (name, rank, RRF score, timing).'
        ),
    )


class StrategyDebugInfo(BaseModel):
    """Per-strategy attribution for a single retrieval result."""

    strategy_name: str = Field(description='Name of the strategy that contributed this result.')
    rank: int = Field(description='Rank of this result within the strategy (1-based).')
    rrf_score: float = Field(description='RRF contribution score from this strategy.')
    raw_score: float | None = Field(
        default=None, description='Raw score from the strategy (distance, BM25, etc.).'
    )
    timing_ms: float | None = Field(
        default=None, description='Time taken by this strategy in milliseconds.'
    )


class ReflectionRequest(VaultMixin):
    """
    Request to run the reflection loop on a specific entity.
    """

    entity_id: UUID = Field(description='The UUID of the entity to reflect upon.')
    limit_recent_memories: int = Field(
        default=20, description='Number of recent memories to consider.'
    )


class IngestURLRequest(VaultMixin):
    """Request to ingest content from a URL."""

    url: str = Field(..., description='The URL to ingest.')
    reflect_after: bool = Field(
        default=True, description='Whether to run reflection after ingestion.'
    )
    assets: dict[str, str] = Field(
        default_factory=dict,
        description='Optional dictionary of assets (filename -> base64 content).',
    )
    user_notes: str | None = Field(
        default=None,
        description='Optional user-provided context or commentary to include in the note.',
    )


class IngestFileRequest(VaultMixin):
    """Request to ingest content from a local file path (server-side)."""

    file_path: str = Field(..., description='The absolute path to the file on the server.')
    reflect_after: bool = Field(
        default=True, description='Whether to run reflection after ingestion.'
    )
    user_notes: str | None = Field(
        default=None,
        description='Optional user-provided context or commentary to include in the note.',
    )


class CreateVaultRequest(BaseModel):
    """Request to create a new vault."""

    name: str = Field(..., description='The name of the vault.')

    description: str | None = Field(default=None, description='Optional description.')


class MemoryUnitBase(VaultMixin):
    """Base schema for Memory Unit shared between DTOs and SQLModels."""

    text: str = Field(description='The textual content of the memory unit.')
    fact_type: FactTypes = Field(description='The type/category of the memory unit.')
    status: str = Field(
        default='active',
        description='Content status: active or stale.',
        examples=['active', 'stale'],
    )

    mentioned_at: dt.datetime | None = Field(
        default=None, description='The datetime when the memory unit was mentioned.'
    )
    occurred_start: dt.datetime | None = Field(
        default=None, description='The start datetime of when the fact/event occurred.'
    )
    occurred_end: dt.datetime | None = Field(
        default=None, description='The end datetime of when the fact/event occurred.'
    )


class SupersessionInfo(BaseModel):
    """Info about a unit that supersedes this one."""

    unit_id: UUID
    unit_text: str
    note_title: str | None = None
    relation: str  # 'contradicts' | 'weakens'


class MemoryUnitDTO(MemoryUnitBase):
    """DTO for a Memory Unit (Fact/Experience)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(
        description='The unique identifier of the memory unit.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    note_id: UUID | None = Field(
        default=None,
        description='The unique identifier of the source note.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    chunk_id: UUID | None = Field(
        default=None,
        description='The source chunk ID this memory unit was extracted from.',
    )

    node_ids: list[str] = Field(
        default_factory=list,
        description='Page-index node IDs linked to the source chunk.',
    )

    source_note_ids: list[UUID] = Field(
        default_factory=list,
        description='List of source note IDs.',
        examples=[['123e4567-e89b-12d3-a456-426614174000']],
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description='Additional metadata associated with the memory unit.',
        examples=[{'source': 'interview', 'author': 'user'}],
    )

    score: float | None = Field(
        default=None,
        description='Relevance score from retrieval or reranking (0.0 to 1.0).',
        examples=[0.95],
    )

    debug_info: list[StrategyDebugInfo] | None = Field(
        default=None,
        description='Per-strategy attribution when debug=True. None when debug is off.',
    )

    confidence: float = Field(
        default=1.0,
        description='Confidence score (0.0-1.0).',
    )

    superseded_by: list[SupersessionInfo] | None = Field(
        default=None,
        description='Units that supersede this one.',
    )

    @property
    def enriched_text(self) -> str:
        """Text with date metadata for LLM consumption."""
        date = self.mentioned_at or self.occurred_start
        date_str = date.strftime('%Y-%m-%d') if date else 'Unknown'
        return f'[{date_str}] {self.text}'


class ObservationDTO(BaseModel):
    """DTO for an Observation (Mental Model component)."""

    id: UUID | None = Field(
        default=None,
        description='The unique identifier of the observation.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    title: str = Field(
        description='Short title or headline for the observation.',
        examples=['User prefers Python over Java'],
    )

    content: str = Field(
        description='Detailed content of the observation.',
        examples=['The user consistently chooses Python for new projects due to its simplicity.'],
    )

    trend: str | None = Field(
        default=None,
        description='Current trend of this observation (e.g. new, stable, strengthening).',
        examples=['strengthening'],
    )

    evidence: list[dict[str, Any]] = Field(
        default_factory=list,
        description='List of supporting evidence items.',
        examples=[{'memory_id': '...', 'quote': 'I love Python'}],
    )


class EntityDTO(BaseModel):
    """DTO for an Entity."""

    id: UUID = Field(
        description='The unique identifier of the entity.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    name: str = Field(
        description='The canonical name of the entity.',
        examples=['Python'],
    )

    mention_count: int = Field(
        default=0,
        description='Cumulative number of times this entity has been mentioned.',
        examples=[42],
    )

    vault_id: UUID | None = Field(
        default=None,
        description='The UUID of the vault this entity belongs to.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    entity_type: str | None = Field(
        default=None,
        description='The semantic type of the entity (e.g. Person, Organization, Concept).',
        examples=['Person', 'Technology'],
    )

    metadata: dict[str, Any] = Field(
        default={},
        description='Vault-scoped metadata derived from reflection (description, category).',
    )


class VaultDTO(BaseModel):
    """DTO for a Vault."""

    id: UUID = Field(
        description='The unique identifier of the vault.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    name: str = Field(
        description='The name of the vault.',
        examples=['Personal', 'Work'],
    )

    description: str | None = Field(
        default=None,
        description='Optional description of the vault.',
        examples=['My personal memories and notes.'],
    )

    is_active: bool = Field(
        default=False,
        description='Whether this vault is the currently active (writer) vault.',
    )

    note_count: int = Field(
        default=0,
        description='Number of notes in this vault.',
    )

    last_note_added_at: dt.datetime | None = Field(
        default=None,
        description='Timestamp of the most recently added note in this vault.',
    )

    access: list[str] | None = Field(
        default=None,
        description=(
            'Effective permissions for the current API key on this vault. '
            'None when auth is disabled. Example: ["read", "write"].'
        ),
    )


class DefaultVaultsResponse(BaseModel):
    """Response model for the default vaults endpoint."""

    active_vault: VaultDTO = Field(
        description='The active (writer) vault.',
    )
    reader_vaults: list[VaultDTO] = Field(
        default_factory=list,
        description='Default reader vaults for search/retrieval.',
    )


class NoteCreateDTO(BaseModel):
    """DTO for creating a Note artifact (input/ingestion)."""

    name: str = Field(
        description='The name of the note.',
        examples=['Meeting Notes'],
    )
    note_key: str | None = Field(
        default=None,
        description='A unique stable key for the note to enable incremental updates.',
        examples=['my-stable-note-id'],
    )
    description: str = Field(
        description='A brief description or summary of the note.',
        examples=['Notes from the weekly team sync.'],
    )
    content: Base64Bytes = Field(
        description='Base64 encoded content of the note.',
        examples=['VGhpcyBpcyBhIHRlc3Qgbm90ZS4='],
    )
    files: dict[str, Base64Bytes] = Field(
        default_factory=dict,
        description='Dictionary mapping filenames to Base64 encoded content.',
        examples=[
            {
                'image.png': 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
            }
        ],
    )
    tags: list[str] = Field(
        default_factory=list,
        description='List of tags associated with the note.',
        examples=[['meeting', 'work']],
    )
    vault_id: str | UUID | None = Field(
        default=None,
        description='Optional target vault ID or name.',
    )
    user_notes: str | None = Field(
        default=None,
        description='Optional user-provided context or commentary to include in the note.',
    )
    author: str | None = Field(
        default=None,
        description='Author of the note.',
        examples=['alice'],
    )
    template: str | None = Field(
        default=None,
        description='Template slug used to create this note (e.g. "general_note").',
        examples=['general_note', 'technical_brief'],
    )
    filename: str | None = Field(
        default=None,
        description='Original filename of the content (e.g. "report.pdf"). '
        'When present and the extension is not .md, the server converts '
        'the content to Markdown before ingestion using FileContentProcessor.',
        examples=['report.pdf', 'slides.pptx', 'meeting-notes.md'],
    )

    @property
    def content_decoded(self) -> bytes:
        """Return the decoded raw bytes of the note content."""
        return base64.b64decode(self.content)

    @property
    def files_decoded(self) -> dict[str, bytes]:
        """Return a dictionary of filenames to decoded raw bytes."""
        return {k: base64.b64decode(v) for k, v in self.files.items()}

    @field_serializer('content')
    def serialize_content(self, content: bytes) -> str:
        try:
            return content.decode('utf-8')
        except UnicodeDecodeError:
            return base64.b64encode(content).decode('ascii')

    @field_serializer('files')
    def serialize_files(self, files: dict[str, bytes]) -> dict[str, str]:
        result: dict[str, str] = {}
        for k, v in files.items():
            try:
                result[k] = v.decode('utf-8')
            except UnicodeDecodeError:
                result[k] = base64.b64encode(v).decode('ascii')
        return result


class OverlappingNote(BaseModel):
    """A note that overlaps with the newly ingested one."""

    note_id: UUID
    similarity: float
    title: str | None = None


class IngestResponse(BaseModel):
    """Response from ingestion."""

    status: str = Field(
        description='Status of the ingestion operation.',
        examples=['success', 'skipped', 'failed'],
    )

    note_id: str | None = Field(
        default=None,
        description='The unique identifier of the ingested note.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    unit_ids: list[UUID] = Field(
        default_factory=list,
        description='List of UUIDs for the extracted memory units.',
        examples=[['123e4567-e89b-12d3-a456-426614174001', '123e4567-e89b-12d3-a456-426614174002']],
    )

    reason: str | None = Field(
        default=None,
        description='Reason for skipping or failure, if applicable.',
        examples=['idempotency_check'],
    )

    overlapping_notes: list[OverlappingNote] = Field(
        default_factory=list,
        description='Notes with high similarity to the ingested content (>0.85).',
    )


class WebhookPayload(BaseModel):
    """Payload accepted by the webhook ingestion endpoint."""

    title: str = Field(
        description='Title of the note to ingest.',
        examples=['Daily standup notes'],
    )
    content: str = Field(
        description='Plain-text or Markdown content of the note.',
        examples=['## Summary\nWe discussed the roadmap.'],
    )
    source: str = Field(
        description='Identifier for the sending system (used for idempotent note_key generation).',
        examples=['slack-bot', 'github-webhook', 'zapier'],
    )
    description: str | None = Field(
        default=None,
        description='Optional description or summary of the note.',
    )
    tags: list[str] = Field(
        default_factory=list,
        description='Optional tags to associate with the note.',
        examples=[['meeting', 'standup']],
    )
    vault_id: str | UUID | None = Field(
        default=None,
        description='Optional target vault ID or name.',
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description='Arbitrary metadata from the webhook source.',
    )


class ReflectionResultDTO(BaseModel):
    """DTO for reflection results."""

    entity_id: UUID = Field(
        description='The UUID of the entity reflected upon.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )

    new_observations: list[ObservationDTO] = Field(
        description='List of new observations generated during reflection.',
    )

    status: str = Field(
        default='success',
        description='Status of the reflection operation.',
        examples=['success', 'failed'],
    )


class ReflectionQueueDTO(BaseModel):
    """DTO for reflection queue item."""

    entity_id: UUID = Field(
        description='The UUID of the entity in the queue.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    vault_id: UUID = Field(
        description='The UUID of the vault associated with the entity.',
        examples=['123e4567-e89b-12d3-a456-426614174000'],
    )
    priority_score: float = Field(
        default=0.0,
        description='Priority score for processing.',
        examples=[0.85],
    )


class DeadLetterItemDTO(BaseModel):
    """DTO for a dead-lettered reflection queue item."""

    id: UUID = Field(description='Queue item ID.')
    entity_id: UUID = Field(description='Entity that failed reflection.')
    vault_id: UUID = Field(description='Vault of the entity.')
    priority_score: float = Field(default=0.0, description='Priority score.')
    retry_count: int = Field(default=0, description='Number of retries attempted.')
    max_retries: int = Field(default=3, description='Maximum retries before dead letter.')
    last_error: str | None = Field(default=None, description='Last error message.')
    status: str = Field(default='dead_letter', description='Current status.')


class BatchIngestRequest(BaseModel):
    """Request for batch ingestion of notes."""

    notes: list[NoteCreateDTO] = Field(..., description='List of notes to ingest.')
    vault_id: UUID | str | None = Field(
        default=None,
        description='Optional target vault ID or name that overrides note-level vault.',
    )
    batch_size: int = Field(default=32, description='Internal processing chunk size.', ge=1, le=100)


class BatchIngestResponse(BaseModel):
    """Final response from a batch ingestion operation."""

    processed_count: int = Field(default=0, description='Number of successfully processed notes.')
    skipped_count: int = Field(default=0, description='Number of skipped notes (e.g. duplicates).')
    failed_count: int = Field(default=0, description='Number of notes that failed to process.')
    note_ids: list[str] = Field(default_factory=list, description='List of created Note UUIDs.')
    errors: list[dict[str, Any]] = Field(
        default_factory=list, description='Detailed error information indexed by input.'
    )


class BatchJobStatus(BaseModel):
    """Current status of an asynchronous batch job."""

    job_id: UUID = Field(..., description='The unique identifier of the batch job.')
    status: str = Field(
        ...,
        description='Current status of the job.',
        examples=['pending', 'processing', 'completed', 'failed'],
    )
    progress: str | None = Field(default=None, description='Optional human-readable progress info.')
    processed_count: int | None = Field(
        default=None, description='Notes processed so far (including skipped/failed).'
    )
    total_count: int | None = Field(default=None, description='Total notes in the batch.')
    result: BatchIngestResponse | None = Field(
        default=None, description='Final results, available when status is "completed".'
    )


class SystemStatsCountsDTO(BaseModel):
    """Counts for system entities."""

    notes: int = Field(default=0, description='Total number of notes (documents).')
    memories: int = Field(description='Total number of memory units.')
    entities: int = Field(description='Total number of entities.')
    reflection_queue: int = Field(description='Number of items in the reflection queue.')


class NodeDTO(BaseModel):
    """DTO for a note node (section produced by PageIndex)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    note_id: UUID
    vault_id: UUID
    node_hash: str | None = None
    title: str
    text: str
    level: int
    seq: int
    status: str
    created_at: dt.datetime


class NoteDTO(BaseModel):
    """DTO for a Note (output/retrieval)."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    title: str | None = None
    name: str | None = None
    original_text: str | None = None
    created_at: dt.datetime
    publish_date: dt.datetime | None = None
    vault_id: UUID
    vault_name: str | None = None
    description: str | None = None
    assets: list[str] = Field(default_factory=list)
    doc_metadata: dict[str, Any] = Field(default_factory=dict)
    template: str | None = None


class BlockSummaryDTO(BaseModel):
    """Block-level summary from extraction."""

    topic: str
    key_points: list[str] = Field(default_factory=list)


class NoteListItemDTO(BaseModel):
    """Lightweight DTO for note listing — summaries instead of full text."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    title: str | None = None
    name: str | None = None
    created_at: dt.datetime
    publish_date: dt.datetime | None = None
    vault_id: UUID
    vault_name: str | None = None
    description: str | None = None
    assets: list[str] = Field(default_factory=list)
    doc_metadata: dict[str, Any] = Field(default_factory=dict)
    template: str | None = None
    summaries: list[BlockSummaryDTO] = Field(default_factory=list)


class NoteSearchResult(BaseModel):
    """Result of a note search."""

    note_id: UUID
    metadata: dict[str, Any]
    summaries: list[BlockSummaryDTO] = Field(default_factory=list)
    score: float = 0.0
    vault_id: UUID | None = None
    vault_name: str | None = None
    reasoning: list[dict[str, Any]] | None = Field(
        default=None,
        description='Identified sections with reasoning text and node IDs (populated when reason=True).',
    )
    answer: str | None = Field(
        default=None,
        description='LLM-generated answer when summarize=True.',
    )
    note_status: str | None = Field(
        default=None,
        description='Derived status: active, partially_superseded, superseded.',
    )


class NoteSearchRequest(BaseModel):
    """Request to search for notes."""

    query: str
    limit: int = 10
    vault_ids: list[UUID | str] | None = None
    expand_query: bool = False
    fusion_strategy: str = 'rrf'
    strategies: list[str] = Field(default=['semantic', 'keyword', 'graph', 'temporal'])
    strategy_weights: dict[str, float] | None = Field(default=None)
    after: dt.datetime | None = Field(
        default=None, description='Only return notes created after this date (ISO 8601).'
    )
    before: dt.datetime | None = Field(
        default=None, description='Only return notes created before this date (ISO 8601).'
    )
    tags: list[str] | None = Field(
        default=None, description='Only return notes with ALL of these tags.'
    )
    reason: bool = Field(
        default=False,
        description='Run skeleton-tree identification — returns reasoning + relevant section IDs.',
    )
    summarize: bool = Field(
        default=False,
        description='Synthesize a full answer from identified sections (implies reason=True).',
    )
    rerank: bool = Field(
        default=True,
        description='Apply cross-encoder reranking when a reranker is available.',
    )
    mmr_lambda: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            'MMR lambda for relevance-diversity trade-off. '
            '1.0 = pure relevance, 0.0 = max diversity. '
            'None = use server config default (which itself defaults to 0.8).'
        ),
    )

    @model_validator(mode='after')
    def _ensure_reason_if_summarize(self) -> 'NoteSearchRequest':
        if self.summarize:
            self.reason = True
        return self


class SummaryRequest(BaseModel):
    """Request for AI-generated summary of search results."""

    query: str = Field(..., description='The original search query.')
    texts: list[str] = Field(
        ...,
        description='Search result texts to summarize.',
        max_length=50,
    )


class SummaryResponse(BaseModel):
    """Response containing an AI-generated summary with citations."""

    summary: str = Field(
        description='AI-generated summary with bracket citations (e.g. [0], [1]).',
    )


class VaultSummaryDTO(BaseModel):
    """DTO for a vault-level summary."""

    id: UUID = Field(description='Unique identifier for the vault summary.')
    vault_id: UUID = Field(description='The vault this summary describes.')
    summary: str = Field(description='Natural language summary of vault contents.')
    topics: list[dict[str, Any]] = Field(
        description='Extracted topics: [{name, note_count, description}].'
    )
    stats: dict[str, Any] = Field(description='Aggregate vault statistics.')
    version: int = Field(description='Summary version number.')
    notes_incorporated: int = Field(description='Number of notes incorporated.')
    created_at: dt.datetime = Field(description='When the summary was created.')
    updated_at: dt.datetime = Field(description='When the summary was last updated.')


class PageMetadataDTO(BaseModel):
    """Metadata from a note's page index."""

    title: str | None = None
    description: str | None = None
    tags: list[str] = Field(default_factory=list)
    publish_date: str | None = None
    source_uri: str | None = None
    has_assets: bool = False
    vault_id: UUID | None = None
    vault_name: str | None = None
    total_tokens: int | None = None


class SectionSummaryDTO(BaseModel):
    """5W summary of a document section."""

    who: str | None = None
    what: str | None = None
    how: str | None = None
    when: str | None = None
    where: str | None = None


class TOCNodeDTO(BaseModel):
    """A node in the page index table-of-contents."""

    id: str
    title: str
    level: int
    summary: SectionSummaryDTO | None = None
    token_estimate: int | None = None
    subtree_tokens: int | None = None
    children: list['TOCNodeDTO'] = Field(default_factory=list)


class PageIndexDTO(BaseModel):
    """Full page index with metadata and TOC."""

    metadata: PageMetadataDTO
    toc: list[TOCNodeDTO]
    total_tokens: int | None = None


class KVEntryDTO(BaseModel):
    """DTO for a key-value store entry."""

    id: UUID
    key: str
    value: str
    created_at: dt.datetime
    updated_at: dt.datetime


class KVPutRequest(BaseModel):
    """Request to create or update a key-value entry."""

    key: str
    value: str
    embedding: list[float] | None = None


class KVSearchRequest(BaseModel):
    """Request to semantically search key-value entries."""

    query: str
    namespaces: list[str] | None = None
    limit: int = Field(5, ge=1, le=500)


class FindNoteResult(BaseModel):
    """Result from a fuzzy title search over notes."""

    note_id: UUID
    title: str
    score: float
    vault_id: UUID
    created_at: dt.datetime
    publish_date: dt.datetime | None = None
    status: str


# ---------------------------------------------------------------------------
# TOC filtering utility
# ---------------------------------------------------------------------------


def filter_toc(
    toc: list[dict[str, Any]],
    depth: int | None = None,
    parent_node_id: str | None = None,
) -> list[dict[str, Any]]:
    """Filter a TOC tree by depth and/or parent node.

    Pure function — no I/O.  Shared by core (NoteService) and MCP server so
    that both layers can apply the same filtering without MCP importing core
    internals.
    """
    if parent_node_id is not None:

        def _find_subtree(
            nodes: list[dict[str, Any]], target_id: str
        ) -> list[dict[str, Any]] | None:
            for node in nodes:
                if node.get('id') == target_id:
                    return node.get('children', [])
                found = _find_subtree(node.get('children', []), target_id)
                if found is not None:
                    return found
            return None

        subtree = _find_subtree(toc, parent_node_id)
        if subtree is None:
            return []
        toc = subtree

    if depth is not None and depth >= 0:
        # depth=0 -> roots + direct children (H1 + H2 overview)
        # depth=1 -> full tree (no trimming)
        # depth=N (N>=1) -> full tree
        effective_depth = depth + 1

        def _trim_depth(nodes: list[dict[str, Any]], current: int) -> list[dict[str, Any]]:
            if current > effective_depth:
                return []
            result = []
            for node in nodes:
                trimmed = dict(node)
                trimmed['children'] = _trim_depth(node.get('children', []), current + 1)
                result.append(trimmed)
            return result

        if depth == 0:
            toc = _trim_depth(toc, 0)
        # depth >= 1: return full tree (no trimming needed)

    return toc
